data:extend({  --This makes all the custom items this mod adds available for use 

    {--  Green Steel
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/green-steel.png",
        icon_mipmaps=4,
        icon_size=64,
        name="green-steel",
        order="greerzz",
        stack_size=100,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/green-steel.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/green-steel-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Greer Chunks
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-chunks.png",
        icon_mipmaps=4,
        icon_size=64,
        name="greer-chunks",
        order="greeraa",
        stack_size=25,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-chunks.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-chunks-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Coarse Greer Powder
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/coarse-greer-powder.png",
        icon_mipmaps=4,
        icon_size=64,
        name="coarse-greer-powder",
        order="greerab",
        stack_size=30,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/coarse-greer-powder.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/coarse-greer-powder-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Coarse Greer Sandcastle
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/coarse-greer-sandcastle.png",
        icon_mipmaps=4,
        icon_size=64,
        name="coarse-greer-sandcastle",
        order="greerac",
        stack_size=25,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/coarse-greer-sandcastle.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/coarse-greer-sandcastle-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Burnt Coarse Greer Sandcastle
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/burnt-coarse-greer-sandcastle.png",
        icon_mipmaps=4,
        icon_size=64,
        name="burnt-coarse-greer-sandcastle",
        order="greerad",
        stack_size=20,
        subgroup="greer-intermediates",
        type="item"
    },

    {--  Fine Greer Powder
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/fine-greer-powder.png",
        icon_mipmaps=4,
        icon_size=64,
        name="fine-greer-powder",
        order="greerae",
        stack_size=35,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/fine-greer-powder.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/coarse-greer-powder-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Fine Greer Sandcastle
    icon="__hendriks-trains-go-tsssjjj__/graphics/icons/fine-greer-sandcastle.png",
    icon_mipmaps=4,
    icon_size=64,
    name="fine-greer-sandcastle",
    order="greeraf",
    stack_size=30,
    subgroup="greer-intermediates",
    type="item",
    pictures= 
    {
        layers= 
        {
            {
                filename="__hendriks-trains-go-tsssjjj__/graphics/icons/fine-greer-sandcastle.png",
                mipmap_count=4,
                scale=0.25,
                size=64
            },
            {
                draw_as_light=true,
                filename="__hendriks-trains-go-tsssjjj__/graphics/icons/coarse-greer-sandcastle-light.png",
                flags={"light"},
                mipmap_count=4,
                scale=0.25,
                size=64
            }
        }
    }
    },

    {--  Fine Greer Block
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/fine-greer-block.png",
        icon_mipmaps=4,
        icon_size=64,
        name="fine-greer-block",
        order="greerag",
        stack_size=40,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/fine-greer-block.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/fine-greer-block-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Greer Reacting Cell
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-reacting-cell.png",
        icon_mipmaps=4,
        icon_size=64,
        name="greer-reacting-cell",
        order="greerah",
        stack_size=20,
        fuel_category="nuclear",
        burnt_result="used-greer-reacting-cell",
        fuel_value="1GJ",
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-reacting-cell.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__base__/graphics/icons/uranium-fuel-cell-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Used Greer Reacting Cell
        icon="__base__/graphics/icons/used-up-uranium-fuel-cell.png",
        icon_mipmaps=4,
        icon_size=64,
        name="used-greer-reacting-cell",
        order="greerai",
        stack_size=20,
        subgroup="greer-intermediates",
        type="item"
    },

    {--  Solid Greer Mound
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/solid-greer-mound.png",
        icon_mipmaps=4,
        icon_size=64,
        name="solid-greer-mound",
        order="greeraj",
        stack_size=45,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/solid-greer-mound.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/solid-greer-mound-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Soft Solid Greer Mound
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/soft-solid-greer-mound.png",
        icon_mipmaps=4,
        icon_size=64,
        name="soft-solid-greer-mound",
        order="greerak",
        stack_size=45,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/soft-solid-greer-mound.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/solid-greer-mound-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Soft Steel Plate
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/soft-steel-plate.png",
        icon_mipmaps=4,
        icon_size=64,
        name="soft-steel-plate",
        order="greeral",
        stack_size=100,
        subgroup="greer-intermediates",
        type="item"
    },

    {--  Soft Plastic Bar
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/soft-plastic-bar.png",
        icon_mipmaps=4,
        icon_size=64,
        name="soft-plastic-bar",
        order="greeram",
        stack_size=100,
        subgroup="greer-intermediates",
        type="item"
    },

    {--  Greer Steel Blend
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-steel-blend.png",
        icon_mipmaps=4,
        icon_size=64,
        name="greer-steel-blend",
        order="greeran",
        stack_size=50,
        subgroup="greer-intermediates",
        type="item",
        rocket_launch_product={"cool-greer-steel-blend",1},
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-steel-blend.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/solid-greer-mound-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Cool Greer Steel Blend
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-steel-blend.png",
        icon_mipmaps=4,
        icon_size=64,
        name="cool-greer-steel-blend",
        order="greerao",
        stack_size=50,
        subgroup="greer-intermediates",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-steel-blend.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/solid-greer-mound-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Cup O Greer
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/cup-o-greer.png",
        icon_mipmaps=4,
        icon_size=64,
        name="cup-o-greer",
        order="greerap",
        stack_size=200,
        subgroup="science-pack",
        type="item",
        pictures= 
        {
            layers= 
            {
                {
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/cup-o-greer.png",
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                },
                {
                    draw_as_light=true,
                    filename="__hendriks-trains-go-tsssjjj__/graphics/icons/cup-o-greer-light.png",
                    flags={"light"},
                    mipmap_count=4,
                    scale=0.25,
                    size=64
                }
            }
        }
    },

    {--  Plastic Cup
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/plastic-cup.png",
        icon_mipmaps=4,
        icon_size=64,
        name="plastic-cup",
        order="greeraq",
        stack_size=200,
        subgroup="greer-intermediates",
        type="item"
    },

})