data:extend({  --This makes all the custom recipes this mod adds available for use 

    {--  Greer Chunk Seperation   
        name="greer-chunk-seperation",
        type="recipe",
        category="centrifuging",
        enabled=false,
        main_product="greer-chunks",
        energy_required=24,
        ingredients=
        {
            {"uranium-ore",20},
        },
        results=
        {
            {
                name="greer-chunks",
                amount=2,
                probability=0.1
            },
            {
                name="uranium-ore",
                amount=9,
                probability=0.9
            },
        }
    },

    {--  Greer Chunk Crushing   
        name="greer-chunk-crushing",
        type="recipe",
        category="advanced-crafting",
        enabled=false,
        main_product="coarse-greer-powder",
        energy_required=28,
        ingredients=
        {
            {"greer-chunks",21},
        },
        results=
        {
            {
                name="coarse-greer-powder",
                amount=14,
                probability=0.2
            },
        }
    },

    {--  Coarse Greer Sandcastle Making   
        name="coarse-greer-sandcastle-making",
        type="recipe",
        category="advanced-crafting",
        enabled=false,
        main_product="coarse-greer-sandcastle",
        energy_required=30,
        ingredients=
        {
            {"coarse-greer-powder",26},
        },
        results=
        {
            {
                name="coarse-greer-sandcastle",
                amount=12,
                probability=0.21
            },
            {
                name="coarse-greer-powder",
                amount=6,
                probability=0.84
            },
        }
    },

    {--  Coarse Greer Sandcastle Burning   
        name="coarse-greer-sandcastle-burning",
        type="recipe",
        category="smelting",
        enabled=false,
        main_product="burnt-coarse-greer-sandcastle",
        energy_required=10,
        ingredients=
        {
            {"coarse-greer-sandcastle",1},
        },
        results=
        {
            {
                name="burnt-coarse-greer-sandcastle",
                amount=1,
                probability=0.15
            },
        }
    },

    {--  Fine Greer Powder Extraction   
        name="fine-greer-powder-extraction",
        type="recipe",
        category="chemistry",
        enabled=false,
        main_product="fine-greer-powder",
        energy_required=45,
        crafting_machine_tint=
        {
            primary={r=0,g=1,b=0,a=0.75},
            secondary={r=0,g=1,b=0,a=0.75},
            tertiary={r=0,g=1,b=0,a=0.75},
            quaternary={r=0,g=1,b=0,a=0.75},
        },
        ingredients=
        {
            {"burnt-coarse-greer-sandcastle",1},
            {
                type="fluid",
                name="sulfuric-acid",
                amount=250
            },
            {
                type="fluid",
                name="water",
                amount=500
            }
        },
        results=
        {
            {
                name="fine-greer-powder",
                amount=1,
                probability=0.2
            },
        }
    },

    {--  Fine Greer Sandcastle Making   
        name="fine-greer-sandcastle-making",
        type="recipe",
        category="advanced-crafting",
        enabled=false,
        main_product="fine-greer-sandcastle",
        energy_required=60,
        ingredients=
        {
            {"fine-greer-powder",27},
        },
        results=
        {
            {
                name="fine-greer-sandcastle",
                amount=6,
                probability=0.21
            },
            {
                name="fine-greer-powder",
                amount=3,
                probability=0.84
            },
        }
    },

    {--  Fine Greer Block Pressing   
        name="fine-greer-block-pressing",
        type="recipe",
        category="advanced-crafting",
        enabled=false,
        main_product="fine-greer-block",
        energy_required=36,
        ingredients=
        {
            {"fine-greer-sandcastle",8},
        },
        results=
        {
            {
                name="fine-greer-block",
                amount=1,
                probability=0.37
            },
            {
                name="fine-greer-powder",
                amount=2,
                probability=0.84
            },
        }
    },

    {--  Greer Reacting Cell Making   
        name="greer-reacting-cell-making",
        type="recipe",
        category="crafting-with-fluid",
        enabled=false,
        main_product="greer-reacting-cell",
        energy_required=60,
        ingredients=
        {
            {"fine-greer-block",5},
            {"steel-plate",20},
            {"plastic-bar",10},
            {
                type="fluid",
                name="sulfuric-acid",
                amount=1000
            },
        },
        results=
        {
            {"greer-reacting-cell",1},
        }
    },

    {--  Solid Greer Mound Extraction   
        name="solid-greer-mound-extraction",
        type="recipe",
        category="chemistry",
        enabled=false,
        main_product="solid-greer-mound",
        energy_required=30,
        crafting_machine_tint=
        {
            primary={r=0,g=1,b=0,a=0.75},
            secondary={r=0,g=1,b=0,a=0.75},
            tertiary={r=0,g=1,b=0,a=0.75},
            quaternary={r=0,g=1,b=0,a=0.75},
        },
        ingredients=
        {
            {"used-greer-reacting-cell",1},
            {
                type="fluid",
                name="sulfuric-acid",
                amount=250
            },
            {
                type="fluid",
                name="water",
                amount=500
            }
        },
        results=
        {
            {
                name="solid-greer-mound",
                amount=1,
                probability=0.2
            },
        }
    },

    {--  Solid Greer Mound Softening   
        name="solid-greer-mound-softening",
        type="recipe",
        category="smelting",
        enabled=false,
        main_product="soft-solid-greer-mound",
        energy_required=10,
        ingredients=
        {
            {"solid-greer-mound",1},
        },
        results=
        {
            {"soft-solid-greer-mound",1},
        }
    },

    {--  Steel Plate Softening   
        name="steel-plate-softening",
        type="recipe",
        category="smelting",
        enabled=false,
        main_product="soft-steel-plate",
        energy_required=10,
        ingredients=
        {
            {"steel-plate",1},
        },
        results=
        {
            {"soft-steel-plate",1},
        }
    },

    {--  Plastic Bar Softening   
        name="plastic-bar-softening",
        type="recipe",
        category="smelting",
        enabled=false,
        main_product="soft-plastic-bar",
        energy_required=10,
        ingredients=
        {
            {"plastic-bar",1},
        },
        results=
        {
            {"soft-plastic-bar",1},
        }
    },

    {--  Plastic Cup Forming   
        name="plastic-cup-forming",
        type="recipe",
        category="crafting-with-fluid",
        enabled=false,
        main_product="plastic-cup",
        energy_required=30,
        ingredients=
        {
            {"soft-plastic-bar",5},
            {
                type="fluid",
                name="water",
                amount=100
            },
        },
        results=
        {
            {
                name="plastic-cup",
                amount=1,
                probability=0.5
            },
            {
                name="plastic-bar",
                amount=2,
                probability=0.5
            },
        }
    },

    {--  Cup O' Greer Making   
        name="cup-o-greer-making",
        type="recipe",
        category="advanced-crafting",
        enabled=false,
        main_product="cup-o-greer",
        energy_required=15,
        ingredients=
        {
            {"soft-solid-greer-mound",1},
            {"plastic-cup",1},
        },
        results=
        {
            {"cup-o-greer",1},
        }
    },

    {--  Greer-Steel Blend Making   
        name="greer-steel-blend-making",
        type="recipe",
        category="crafting-with-fluid",
        enabled=false,
        main_product="greer-steel-blend",
        energy_required=60,
        ingredients=
        {
            {"soft-steel-plate",10},
            {"soft-solid-greer-mound",10},
            {
                type="fluid",
                name="sulfuric-acid",
                amount=250
            },
        },
        results=
        {
            {"greer-steel-blend",1},
        }
    },

    {--  Green Steel Smelting   
        name="green-steel-smelting",
        type="recipe",
        category="smelting",
        enabled=false,
        main_product="green-steel",
        energy_required=10,
        ingredients=
        {
            {"cool-greer-steel-blend",1},
        },
        results=
        {
            {"green-steel",1},
        }
    },

})