data:extend({  --This adds all the custom technologies this mod adds to the game

    {--  Basic Greer Processing
        name="basic-greer-processing",
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-chunks.png",
        icon_mipmaps=4,
        icon_size=64,
        effects= 
        {
            {
                recipe="greer-chunk-seperation",
                type="unlock-recipe"
            },
            {
                recipe="greer-chunk-crushing",
                type="unlock-recipe"
            },
            {
                recipe="coarse-greer-sandcastle-making",
                type="unlock-recipe"
            },
            {
                recipe="coarse-greer-sandcastle-burning",
                type="unlock-recipe"
            }
        },
        prerequisites= 
        {
            "uranium-processing",
        },
        type="technology",
        unit= 
        {
            count=250,
            ingredients= 
            {
                {"automation-science-pack",1},
                {"logistic-science-pack",1},
                {"chemical-science-pack",1}
            },
            time=30
        }
    },

    {--  Advanced Greer Processing
        name="advanced-greer-processing",
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/fine-greer-powder.png",
        icon_mipmaps=4,
        icon_size=64,
        effects= 
        {
            {
                recipe="fine-greer-powder-extraction",
                type="unlock-recipe"
            },
            {
                recipe="fine-greer-sandcastle-making",
                type="unlock-recipe"
            },
            {
                recipe="fine-greer-block-pressing",
                type="unlock-recipe"
            },
            {
                recipe="greer-reacting-cell-making",
                type="unlock-recipe"
            }
        },
        prerequisites= 
        {
            "basic-greer-processing",
            "nuclear-power",
        },
        type="technology",
        unit= 
        {
            count=500,
            ingredients= 
            {
                {"automation-science-pack",1},
                {"logistic-science-pack",1},
                {"chemical-science-pack",1},
            },
            time=30
        }
    },
    
    {--  Basic Material Manipulation
        name="basic-material-manipulation",
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/soft-steel-plate.png",
        icon_mipmaps=4,
        icon_size=64,
        effects= 
        {
            {
                recipe="solid-greer-mound-extraction",
                type="unlock-recipe"
            },
            {
                recipe="solid-greer-mound-softening",
                type="unlock-recipe"
            },
            {
                recipe="steel-plate-softening",
                type="unlock-recipe"
            },
            {
                recipe="plastic-bar-softening",
                type="unlock-recipe"
            }
        },
        prerequisites= 
        {
            "advanced-greer-processing",
            "automation-3",
        },
        type="technology",
        unit= 
        {
            count=550,
            ingredients= 
            {
                {"automation-science-pack",1},
                {"logistic-science-pack",1},
                {"chemical-science-pack",1},
                {"production-science-pack",1},
            },
            time=60
        }
    },

    {--  Advanced Material Manipulation
        name="advanced-material-manipulation",
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/greer-steel-blend.png",
        icon_mipmaps=4,
        icon_size=64,
        effects= 
        {
            {
                recipe="greer-steel-blend-making",
                type="unlock-recipe"
            },
            {
                recipe="plastic-cup-forming",
                type="unlock-recipe"
            },
            {
                recipe="cup-o-greer-making",
                type="unlock-recipe"
            },
        },
        prerequisites= 
        {
            "basic-material-manipulation",
            "kovarex-enrichment-process",
        },
        type="technology",
        unit= 
        {
            count=1500,
            ingredients= 
            {
                {"automation-science-pack",1},
                {"logistic-science-pack",1},
                {"chemical-science-pack",1},
                {"production-science-pack",1},
                {"utility-science-pack",1},
            },
            time=30
        }
    },

    {--  Green Steel Smelting
        name="green-steel-smelting",
        icon="__hendriks-trains-go-tsssjjj__/graphics/icons/green-steel.png",
        icon_mipmaps=4,
        icon_size=64,
        effects= 
        {
            {
                recipe="green-steel-smelting",
                type="unlock-recipe"
            },
        },
        prerequisites= 
        {
            "advanced-material-manipulation",
            "rocket-silo",
        },
        type="technology",
        unit= 
        {
            count=42,
            ingredients= 
            {
                {"cup-o-greer",1},
                {"space-science-pack",1}
            },
            time=42
        }
    },

})